name: nbtc_frontend
description: A Flutter client for the NBTC backend.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.3.1
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/nbtc_logo.jpg
